CC := gcc
CCFLAGS := -pedantic -Wall -Werror -g `sdl2-config --cflags --libs` -lSDL2_image -lGL -lGLEW -lGLU -lm -DDATADIR=\"data\"

SRCDIRS := src
SOURCES := $(foreach DIR, $(SRCDIRS), $(wildcard $(DIR)/*.c))
TARGET := bin/OpenPandemic

.PHONY: all
.PHONY: clean

all: $(TARGET)

clean:
	rm -f $(TARGET)

$(TARGET): $(SOURCES)
	mkdir -p $(@D)
	$(CC) -o $(TARGET) $(SOURCES) $(CCFLAGS)
